etcd:
  image: gcr.io/google_containers/etcd:2.0.13
  net: "host"
  command: ['/usr/local/bin/etcd', '--bind-addr=0.0.0.0:4001', '--data-dir=/var/etcd/data']

apiserver:
  image: gcr.io/google_containers/hyperkube:v1.1.1-beta.1
  net: "host"
  command: ["/hyperkube", "apiserver", "--service-cluster-ip-range=172.17.17.1/24", "--address=0.0.0.0", "--etcd_servers=http://127.0.0.1:4001", "--cluster_name=hyperion", "--v=2"]

controller:
  image: gcr.io/google_containers/hyperkube:v1.1.1-beta.1
  net: "host"
  command: ["/hyperkube", "controller-manager", "--address=0.0.0.0", "--master=http://127.0.0.1:8080", "--v=2"]

scheduler:
  image: gcr.io/google_containers/hyperkube:v1.1.1-beta.1
  net: "host"
  command: ["/hyperkube", "scheduler", "--address=0.0.0.0", "--master=http://127.0.0.1:8080", "--v=2"]

kubelet:
  image: gcr.io/google_containers/hyperkube:v1.1.1-beta.1
  net: "host"
  command: ['/hyperkube', 'kubelet', '--containerized' , '--api_servers=http://127.0.0.1:8080', '--v=2', '--address=0.0.0.0', '--enable_server']
  volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /dev:/dev
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw
  privileged: true

proxy:
  image: gcr.io/google_containers/hyperkube:v1.1.1-beta.1
  net: "host"
  command: ['/hyperkube', 'proxy', '--master=http://127.0.0.1:8080', '--v=2']
  privileged: true

# apiserver:
#   image: portefaix/hyperkube:1.1.1-beta.1
#   net: host
#   command: ["/hyperkube", "apiserver", "--service-cluster-ip-range=172.17.17.1/24", "--address=127.0.0.1", "--etcd_servers=http://127.0.0.1:4001", "--cluster_name=kubernetes", "--v=2"]

# controller:
#   image: portefaix/hyperkube:1.1.1-beta.1
#   net: host
#   command: ["/hyperkube", "controller-manager", "--master=127.0.0.1:8080", "--v=2"]

# scheduler:
#   image: portefaix/hyperkube:1.1.1-beta.1
#   net: host
#   command: ["/hyperkube", "scheduler", "--master=127.0.0.1:8080", "--v=2"]

# kubelet:
#   image: portefaix/hyperkube:1.1.1-beta.1
#   net: host
#   command: ["/hyperkube", "kubelet", "--api_servers=http://127.0.0.1:8080", "--address=0.0.0.0", "--enable_server", "--v=2"]
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
